name = "LinearElasticity"
uuid = "8b390c8a-e41e-419b-b3a5-595c9a4d2b26"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.1-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Tensorial = "98f94333-fa9f-48a9-ad80-1c66397b2b38"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
Tensorial = "0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10"

[targets]
test = ["Test"]
